import type { NextPage } from 'next';
import { ImageMain } from 'components/common';
import Head from 'next/head';
import { HomeMain } from '.';
import { ProgramWrapper } from 'components/center';

const Center: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeMain>
        <ImageMain />
        <ProgramWrapper />
      </HomeMain>
    </div>
  );
}

export default Center;
