import { NextPage } from 'next';
import Head from 'next/head';
import { HomeMain } from '.';
import { ImageMain, FAQWrapper } from 'components/common';
import { COMMON_FAQ_ITEM } from 'constant/FAQItem';
import { FeatureWrapper, StrengthWrapper, ProcessWrapper } from 'components/pt/Wrapper';

const Pt: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeMain>
        <ImageMain src="/ptB2C.jpg" alt="노리케어 방문 PT" width="1650" height="810" />
        <StrengthWrapper />
        <FeatureWrapper />
        <ProcessWrapper />
        <FAQWrapper title="방문 PT" item={COMMON_FAQ_ITEM} />
      </HomeMain>
    </div>
  );
};

export default Pt;
